mainapp/api/urls.py
from django.urls import path

from .api_views import (
    CategoryAPIView,
    SmartphoneListAPIView,
    NotebookListAPIView,
    SmartphoneDetailAPIView,
    NotebookDetailAPIView,
)


urlpatterns = [
    path('categories/', CategoryAPIView.as_view(), name='categories_list'),
    path('smartphones/', SmartphoneListAPIView.as_view(), name='smartphones_list'),
    path('notebooks/', NotebookListAPIView.as_view(), name='notebooks_list'),
    path('smartphones/<str:id>/', SmartphoneDetailAPIView.as_view(), name='smartphone_detail'),
    path('notebooks/<str:id>/', NotebookDetailAPIView.as_view(), name='notebook_detail'),
]

mainapp/urls.py
from django.urls import path

from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQTYView,
    CheckoutView,
    MakeOrderView,
    PayedOnlineOrderView
)

urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:ct_model>/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:ct_model>/<str:slug>/', AddToCartView.as_view(), name='add-to-cart'),
    path('remove-from-cart/<str:ct_model>/<str:slug>/', DeleteFromCartView.as_view(), name='remove-from-cart'),
    path('change-qty/<str:ct_model>/<str:slug>/', ChangeQTYView.as_view(), name='change-qty'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('payed-online-order/', PayedOnlineOrderView.as_view(), name='payed-online-order'),
]

shop_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('mainapp.api.urls')),
    path('', include('mainapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
import sys
from PIL import Image

from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from django.core.files.uploadedfile import InMemoryUploadedFile
from django.urls import reverse
from django.utils import timezone

from io import BytesIO

User = get_user_model()


def get_models_for_count(*model_names):
    return [models.Count(model_name) for model_name in model_names]


def get_product_url(obj, viewname):
    ct_model = obj.__class__._meta.model_name
    return reverse(viewname, kwargs={'ct_model': ct_model, 'slug': obj.slug})


class MinResolutionErrorException(Exception):
    pass


class MaxResolutionErrorException(Exception):
    pass


class LatestProductsManager:

    @staticmethod
    def get_products_for_main_page(*args, **kwargs):
        with_respect_to = kwargs.get('with_respect_to')
        products = []
        ct_models = ContentType.objects.filter(model__in=args)
        for ct_model in ct_models:
            model_products = ct_model.model_class()._base_manager.all().order_by("-id")[:5]
            products.extend(model_products)
        if with_respect_to:
            ct_model = ContentType.objects.filter(model=with_respect_to)
            if ct_model.exists():
                if with_respect_to in args:
                    return sorted(products, key=lambda x: x.__class__._meta.model_name.startswith(with_respect_to),
                                  reverse=True)
        return products


class LatestProducts:
    objects = LatestProductsManager()


class CategoryManager(models.Manager):
    CATEGORY_NAME_COUNT_NAME = {
        'Notebooks': 'notebook__count',
        'Smartphones': 'smartphone__count'
    }

    def get_queryset(self):
        return super().get_queryset()

    def get_categories_for_left_sidebar(self):
        models = get_models_for_count('notebook', 'smartphone')
        qs = list(self.get_queryset().annotate(*models))
        data = [
            dict(name=c.name, url=c.get_absolute_url(), count=getattr(c, self.CATEGORY_NAME_COUNT_NAME[c.name]))
            for c in qs
        ]
        return data


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Category name")
    slug = models.SlugField(unique=True)
    objects = CategoryManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):
    MIN_RESOLUTION = (400, 400)
    MAX_RESOLUTION = (800, 800)
    MAX_IMAGE_SIZE = 3145728

    class Meta:
        abstract = True

    category = models.ForeignKey(Category, verbose_name="Category", on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name="Name")
    slug = models.SlugField(unique=True)
    image = models.ImageField(verbose_name="Image")
    description = models.TextField(verbose_name="Description", null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Price")

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        image = self.image
        img = Image.open(image)
        new_img = img.convert('RGB')
        resized_new_image = new_img.resize((800, 800), Image.ANTIALIAS)
        filestream = BytesIO()
        resized_new_image.save(filestream, 'JPEG', quality=90)
        filestream.seek(0)
        name = '{}.{}'.format(*self.image.name.split('.'))
        self.image = InMemoryUploadedFile(
            filestream, 'ImageField', name, 'jpeg/image', sys.getsizeof(filestream), None
        )
        super().save(*args, **kwargs)

    # image = self.image
    # img = Image.open(image)
    # min_height, min_width = self.MIN_RESOLUTION
    # max_height, max_width = self.MAX_RESOLUTION
    # if img.height < min_height or img.width < min_width:
    #     raise MinResolutionErrorException('Uploaded image is too small')
    # if img.height > max_height or img.width > max_width:
    #     raise MaxResolutionErrorException('Uploaded image is too big')

    def get_model_name(self):
        return self.__class__.__name__.lower()


class Notebook(Product):
    diagonal = models.CharField(max_length=255, verbose_name="Diagonal")
    display_type = models.CharField(max_length=255, verbose_name="Display type")
    processor_freq = models.CharField(max_length=255, verbose_name="Processor frequency")
    ram = models.CharField(max_length=255, verbose_name="RAM")
    video = models.CharField(max_length=255, verbose_name="Graphics card")
    time_without_charge = models.CharField(max_length=255, verbose_name="Time without charge")

    def __str__(self):
        return "{}: {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class Smartphone(Product):
    diagonal = models.CharField(max_length=255, verbose_name="Diagonal")
    display_type = models.CharField(max_length=255, verbose_name="Display type")
    resolution = models.CharField(max_length=255, verbose_name="Resolution")
    accum_volume = models.CharField(max_length=255, verbose_name="Accumulator volume")
    ram = models.CharField(max_length=255, verbose_name="RAM")
    sd = models.BooleanField(default=True, verbose_name="Presence of SD card")
    sd_volume_max = models.CharField(max_length=255, verbose_name="Maximum SD volume", null=True, blank=True)
    main_cam_mp = models.CharField(max_length=255, verbose_name="Main camera (mp)")
    front_cam_mp = models.CharField(max_length=255, verbose_name="Front camera (mp)")

    def __str__(self):
        return "{}: {}".format(self.category.name, self.title)

    def get_absolute_url(self):
        return get_product_url(self, 'product_detail')


class CartProduct(models.Model):
    user = models.ForeignKey('Customer', verbose_name='Customer', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name="Cart", on_delete=models.CASCADE, related_name='related_products')
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    qty = models.PositiveIntegerField(default=1)
    final_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name="Final price")

    def __str__(self):
        return "Product: {} (for Cart)".format(self.content_object.title)

    def save(self, *args, **kwargs):
        self.final_price = self.qty * self.content_object.price
        super().save(*args, **kwargs)


class Cart(models.Model):
    owner = models.ForeignKey("Customer", null=True, verbose_name="Owner", on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    final_price = models.DecimalField(max_digits=9, default=0, decimal_places=2, verbose_name="Final price")
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):
    user = models.ForeignKey(User, verbose_name="User", on_delete=models.CASCADE)
    phone = models.CharField(max_length=20, verbose_name="Phone number", null=True, blank=True)
    address = models.CharField(max_length=255, null=True, blank=True)
    orders = models.ManyToManyField('Order', blank=True, verbose_name='Customer orders', related_name='related_customer')

    def __str__(self):
        return "Customer: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):
    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'ready'
    STATUS_COMPLETED = 'completed'
    STATUS_PAYED = 'payed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_PAYED, 'Order is payed'),
        (STATUS_NEW, 'New order'),
        (STATUS_IN_PROGRESS, 'Order processed'),
        (STATUS_READY, 'Order ready'),
        (STATUS_COMPLETED, 'Order completed'),
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Self pick-up'),
        (BUYING_TYPE_DELIVERY, 'Delivery'),
    )

    customer = models.ForeignKey(Customer, verbose_name='Buyer', related_name='related_orders', on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Name')
    last_name = models.CharField(max_length=255, verbose_name='Surname')
    phone = models.CharField(max_length=20, verbose_name='Phone')
    cart = models.ForeignKey(Cart, verbose_name='Cart', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Address', null=True, blank=True)
    status = models.CharField(max_length=100, verbose_name='Order status', choices=STATUS_CHOICES, default=STATUS_NEW)
    buying_type = models.CharField(max_length=100, verbose_name='Order type', choices=BUYING_TYPE_CHOICES, default=BUYING_TYPE_SELF)
    comment = models.TextField(verbose_name='Comment to order', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Order creation date')
    order_date = models.DateField(verbose_name='Receive date', default=timezone.now)

    def __str__(self):
        return str(self.id)

mainapp/forms.py
from django import forms

from .models import Order


class OrderForm(forms.ModelForm):

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )

mainapp/templates/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
    {{ block.super }}
    <script>
        (function ($) {
            $('#id_sd').on('click', function () {
                if($('#id_sd').prop('checked') == true){
                    $('#id_sd_volume_max').prop('readonly', false)
                    $('#id_sd_volume_max').val('')
                    $('#id_sd_volume_max').css('background', 'white')
                }else {
                    $('#id_sd_volume_max').prop('readonly', true)
                    $('#id_sd_volume_max').val('')
                    $('#id_sd_volume_max').css('background', 'lightgray')
                }
            })
        })(django.jQuery);
    </script>
{% endblock %}

mainapp/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Shop Homepage - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- Stripe -->
    <script src="https://js.stripe.com/v3/"></script>

</head>

<style>
    body {
        padding-top: 56px;
    }
</style>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="#">Start Bootstrap</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart' %}">Cart <span
                            class="badge badge-pill badge-danger">{{ cart.products.count }}</span> </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
<div class="container">

    <div class="row">

        <div class="col-lg-3">

            <h1 class="my-4">Shop Name</h1>
            <div class="list-group">
                {% for category in categories %}
                    <a href="{{ category.url }}" class="list-group-item">{{ category.name }} ({{ category.count }})</a>
                {% endfor %}
            </div>

        </div>
        <!-- /.col-lg-3 -->

        <div class="col-lg-9">
            {% block content %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            <strong>{{ message }}</strong>
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endfor %}
                {% endif %}
                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="{{ product.get_absolute_url }}"><img class="card-img-top"
                                                                              src="{{ product.image.url }}" alt=""></a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                                    </h4>
                                    <h5>${{ product.price }}</h5>
                                    <a href="{% url 'add-to-cart' ct_model=product.get_model_name slug=product.slug %}">
                                        <button class="btn btn-danger">Add to cart</button>
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <!-- /.row -->
            {% endblock content %}
        </div>
        <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
</footer>

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/cart.html
{% extends 'base.html' %}

{% block content %}

    <h3 class="text-center mt-5 mb-5">Your cart {% if not cart.products.count %}is empty{% endif %}</h3>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    {% if cart.products.count %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Image</th>
                <th scope="col">Price</th>
                <th scope="col">Qt.</th>
                <th scope="col">Overall price</th>
                <th scope="col">Action</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart.products.all %}
                <tr>
                    <th scope="row">{{ item.content_object.title }}</th>
                    <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid" alt=""></td>
                    <td>{{ item.content_object.price }} USD</td>
                    <td>
                        <form action="{% url 'change-qty' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}"
                              method="POST">
                            {% csrf_token %}
                            <label>
                                <input type="number" class="form-control" name="qty" style="width: 70px;" min="1"
                                       value="{{ item.qty }}">
                            </label>
                            <br>
                            <input type="submit" class="btn btn-primary" value="change amount">
                        </form>
                    </td>
                    <td>{{ item.final_price }} USD</td>
                    <td>
                        <a href="{% url 'remove-from-cart' ct_model=item.content_object.get_model_name slug=item.content_object.slug %}">
                            <button class="btn btn-danger">Delete</button>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td>Overall:</td>
                <td>{{ cart.total_products }}</td>
                <td><strong>{{ cart.final_price }} USD</strong></td>
                <td><a href="{% url 'checkout' %}">
                    <button class="btn btn-primary">Checkout</button>
                </a></td>
            </tr>
            </tbody>
        </table>
    {% endif %}

{% endblock content %}

mainapp/templates/category_detail.html
{% extends 'base.html' %}


{% block content %}

    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
            <li class="breadcrumb-item active">{{ category.name }}</li>
        </ol>
    </nav>

    <div class="row">
        {% for product in category_products %}
            <div class="col-lg-4 col-md-6 mb-4">
                <div class="card h-100">
                    <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}"
                                                                  alt=""></a>
                    <div class="card-body">
                        <h4 class="card-title">
                            <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                        </h4>
                        <h5>${{ product.price }}</h5>
                        <a href="{% url 'add-to-cart' ct_model=product.get_model_name slug=product.slug %}">
                            <button class="btn btn-danger">Add to cart</button>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}

mainapp/templates/checkout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}

    <h3 class="text-center mt-5 mb-5">Order</h3>

    {% if cart.products.count %}
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Image</th>
                <th scope="col">Price</th>
                <th scope="col">Qt.</th>
                <th scope="col">Overall price</th>
            </tr>
            </thead>
            <tbody>
            {% for item in cart.products.all %}
                <tr>
                    <th scope="row">{{ item.content_object.title }}</th>
                    <td class="w-25"><img src="{{ item.content_object.image.url }}" class="img-fluid" alt=""></td>
                    <td>{{ item.content_object.price }} USD</td>
                    <td>{{ item.qty }}</td>
                    <td>{{ item.final_price }} USD</td>
                </tr>
            {% endfor %}
            <tr>
                <td colspan="2"></td>
                <td>Overall:</td>
                <td>{{ cart.total_products }}</td>
                <td><strong>{{ cart.final_price }} USD</strong></td>
            </tr>
            </tbody>
        </table>
    {% endif %}
    <hr>
    <h3 class="text-center mt-5 mb-5">Order form</h3>

    <div class="row">
        <div class="col-md-6">
            <h3 class="text-center">Order</h3>
            <form action="{% url 'make_order' %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" class="btn btn-success btn-block mb-3" value="Checkout">
            </form>
        </div>
        <div class="col-md-6">
            <h3 class="text-center">Pay for order online</h3>
            <form id="payment-form" name="order">
                <div id="card-element">
                    <!-- Elements will create input elements here -->
                </div>

                <!-- We'll put the error messages in this element -->
                <div id="card-errors" role="alert"></div>

                <button type="submit" data-username="{{ cart.owner.user.username }}" class="btn btn-primary btn-block" id="card-button" data-secret="{{ client_secret }}">Pay</button>
            </form>
        </div>
    </div>
    <script>
        var form = document.getElementById('payment-form');
        var stripe = Stripe('pk_test_51HHvkTJvmisgK0uTHqHzsRzrDtJbzFvQ3KOubWUxcEQ5zGrTgdfL1WrRYJpVbg9NJLJDK8aSnZW7We1WFBhLh9qW00ooB2TM7v');
        var elements = stripe.elements();
        var style = {
            base: {
                color: "#32325d",
            }
        };

        var card = elements.create("card", {style: style});
        card.mount("#card-element");
        card.on('change', function (event) {
            var displayError = document.getElementById('card-errors');
            if (event.error) {
                displayError.textContent = event.error.message;
            } else {
                displayError.textContent = '';
            }
        });
        form.addEventListener('submit', function (ev) {
            ev.preventDefault();
            var clientSecret = document.getElementById('card-button')
            stripe.confirmCardPayment(clientSecret.dataset.secret, {
                payment_method: {
                    card: card,
                    billing_details: {
                        name: document.getElementById('card-button').dataset.username
                    }
                }
            }).then(function (result) {
                if (result.error) {
                    // Show error to your customer (e.g., insufficient funds)
                    console.log(result.error.message);
                } else {
                    // The payment has been processed!
                    if (result.paymentIntent.status === 'succeeded') {
                        function getCookie(name) {
                            let cookieValue = null;
                            if (document.cookie && document.cookie !== '') {
                                const cookies = document.cookie.split(';');
                                for (let i = 0; i < cookies.length; i++) {
                                    const cookie = cookies[i].trim();
                                    // Does this cookie string begin with the name we want?
                                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                        break;
                                    }
                                }
                            }
                            return cookieValue;
                        }

                        const csrftoken = getCookie('csrftoken');
                        var formData = new FormData(document.forms.order);

                        // добавить к пересылке ещё пару ключ - значение
                        formData.append("first_name", document.getElementById('card-button').dataset.username);
                        formData.append("csrfmiddlewaretoken", csrftoken)
                        var xhr = new XMLHttpRequest();
                        xhr.open("POST", "/payed-online-order/");
                        xhr.send(formData);
                        xhr.onreadystatechange = function () {
                            if (xhr.readyState == 4) {
                                window.location.replace("http://127.0.0.1:8000");
                                alert('Ваш заказ успешно оплачен! Менеджер с Вами свяжется')
                            }
                        }
                    }
                }
            });
        });
    </script>

{% endblock content %}

mainapp/templates/notebook_specification.html
<body>
<table class="table">
    <tbody>
    <tr>
        <td>Diagonal:</td>
        <td>{{ product.diagonal }}</td>
    </tr>
    <tr>
        <td>Display type:</td>
        <td>{{ product.display_type }}</td>
    </tr>
    <tr>
        <td>Processor frequency:</td>
        <td>{{ product.processor_freq }}</td>
    </tr>
    <tr>
        <td>RAM:</td>
        <td>{{ product.ram }}</td>
    </tr>
    <tr>
        <td>Video card:</td>
        <td>{{ product.video }}</td>
    </tr>
    <tr>
        <td>Time without charge:</td>
        <td>{{ product.time_without_charge }}</td>
    </tr>
    </tbody>
</table>
</body>

mainapp/templates/product_detail.html
{% extends 'base.html' %}
{% load specifications %}

{% block content %}

    <nav aria-label="breadcrumb" class="mt-3">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'base' %}">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ product.title }}</li>
        </ol>
    </nav>
    <div class="row">
        <div class="col-md-4">
            <img src="{{ product.image.url }}" class="img-fluid" alt="">
        </div>
        <div class="col-md-8">
            <h3>{{ product.title }}</h3>
            <p>Price: {{ product.price }} USD</p>
            <p>Description: {{ product.description }}</p>
            <hr>
            <a href="{% url 'add-to-cart' ct_model=ct_model slug=product.slug %}"><button class="btn btn-danger">Add to cart</button> </a>
        </div>
        <p class="mt-4">Specifications:</p>

        {{ product|product_spec }}

{#        {% if product.category.slug == 'notebooks' %}#}
{#            {% include 'notebook_specification.html' %}#}
{#        {% else %}#}
{#            {% include 'smartphone_specification.html' %}#}
{#        {% endif %}#}

    </div>

{% endblock content %}